from __future__ import annotations

from napari_harpy.widgets.shared_styles import (
    WIDGET_SUCCESS_COLOR,
    WIDGET_WARNING_TEXT_COLOR,
)

HISTOGRAM_PLOT_BACKGROUND_COLOR = "#343944"
HISTOGRAM_AXIS_TEXT_COLOR = "#E1E6EF"
HISTOGRAM_AXIS_GRID_COLOR = "#566071"
HISTOGRAM_BAR_FILL_ALPHA = 195


HISTOGRAM_BAR_FILL_COLOR = "#7EA7FF"
HISTOGRAM_BAR_FILL_ALPHA = 150
HISTOGRAM_BAR_EDGE_COLOR = None
HISTOGRAM_CONTRAST_LINE_COLOR = WIDGET_SUCCESS_COLOR
HISTOGRAM_CONTRAST_REGION_ALPHA = 32
HISTOGRAM_PERCENTILE_LINE_COLOR = WIDGET_WARNING_TEXT_COLOR
