from __future__ import annotations

import numpy as np
from napari.utils.colormaps import DirectLabelColormap


def direct_label_colormap_from_rgba(
    color_dict: dict[int | None, np.ndarray],
    *,
    background_value: int = 0,
) -> DirectLabelColormap:
    """Construct a direct labels colormap from Harpy-generated RGBA arrays.

    Napari's public ``DirectLabelColormap(color_dict=...)`` constructor becomes
    expensive for large labels layers because it validates and color-normalizes
    every ``label_id -> RGBA`` entry. Harpy's styled-labels paths already build
    numeric RGBA arrays, so the large constructor pass is redundant.

    To avoid that bottleneck, construct a tiny normal ``DirectLabelColormap``
    with only the default/background colors so napari/pydantic still initializes
    the model and event emitters correctly. Then install the trusted full RGBA
    mapping directly and clear napari's derived colormap caches.

    This is an internal fast path for RGBA dictionaries generated by Harpy
    itself. It performs only cheap structural checks on the default/background
    entries and does not revalidate every per-label color in the mapping. The
    mapping container and per-label arrays are not copied; callers should treat
    the input mapping and RGBA arrays as immutable after construction.
    """
    if not isinstance(background_value, int) or isinstance(background_value, bool):
        raise ValueError("Labels colormap background value must be an integer label id.")
    if None not in color_dict:
        raise ValueError("Direct labels RGBA color dictionary must include a `None` default color.")
    if background_value not in color_dict:
        raise ValueError(
            f"Direct labels RGBA color dictionary must include background label `{background_value}`."
        )

    _validate_default_color(color_dict[None], label_id=None)
    _validate_default_color(color_dict[background_value], label_id=background_value)
    small_color_dict = {
        None: color_dict[None],
        background_value: color_dict[background_value],
    }
    colormap = DirectLabelColormap(color_dict=small_color_dict, background_value=background_value)
    object.__setattr__(colormap, "color_dict", color_dict)
    colormap._clear_cache()
    return colormap


def _validate_default_color(color: np.ndarray, *, label_id: int | None) -> None:
    if not isinstance(color, np.ndarray):
        raise ValueError(
            f"Direct labels RGBA default/background color for label `{label_id}` must be a numpy array."
        )
    if color.shape != (4,):
        raise ValueError(
            f"Direct labels RGBA default/background color for label `{label_id}` must have shape `(4,)`."
        )
