"""Canonical spatial-query metadata and cache lifecycle."""

from napari_harpy.core.spatial_query.canonical import (
    CANONICAL_ALGORITHM_VERSION,
    CANONICAL_CHANGED_PATHS,
    CANONICAL_OBSM_KEY,
    CANONICAL_SCHEMA_VERSION,
    SPATIAL_COORDINATES_KEY,
    build_canonical_installation_payload,
    build_canonical_metadata,
    build_canonical_region_binding,
    build_canonical_source_signature,
    canonical_metadata_to_storage,
    inspect_canonical_cache,
    install_canonical_cache,
    parse_canonical_metadata,
)
from napari_harpy.core.spatial_query.models import (
    CanonicalCacheMismatch,
    CanonicalCacheReport,
    CanonicalCacheState,
    CanonicalInstallAction,
    CanonicalInstallationPayload,
    CanonicalInstallationResult,
    CanonicalMetadata,
    CanonicalMismatchCode,
    CanonicalRegionBinding,
    CanonicalRegionMetadata,
    CanonicalSourceSignature,
    SpatialDimension,
    build_instance_set_digest,
)

__all__ = [
    "CANONICAL_ALGORITHM_VERSION",
    "CANONICAL_CHANGED_PATHS",
    "CANONICAL_OBSM_KEY",
    "CANONICAL_SCHEMA_VERSION",
    "SPATIAL_COORDINATES_KEY",
    "CanonicalCacheMismatch",
    "CanonicalCacheReport",
    "CanonicalCacheState",
    "CanonicalInstallAction",
    "CanonicalInstallationPayload",
    "CanonicalInstallationResult",
    "CanonicalMetadata",
    "CanonicalMismatchCode",
    "CanonicalRegionBinding",
    "CanonicalRegionMetadata",
    "CanonicalSourceSignature",
    "SpatialDimension",
    "build_canonical_installation_payload",
    "build_canonical_metadata",
    "build_canonical_region_binding",
    "build_canonical_source_signature",
    "build_instance_set_digest",
    "canonical_metadata_to_storage",
    "inspect_canonical_cache",
    "install_canonical_cache",
    "parse_canonical_metadata",
]
