"""Canonical spatial-query metadata and cache lifecycle."""

from napari_harpy.core.spatial_query.canonical import (
    CANONICAL_ALGORITHM_VERSION,
    CANONICAL_AXES,
    CANONICAL_CACHE_PATHS,
    CANONICAL_OBSM_KEY,
    CANONICAL_SCHEMA_VERSION,
    SPATIAL_COORDINATES_KEY,
    apply_canonical_cache_update,
    build_canonical_cache_update_payload,
    build_canonical_metadata,
    build_canonical_region_binding,
    build_canonical_source_signature,
    canonical_metadata_to_storage,
    inspect_canonical_cache,
    parse_canonical_metadata,
)
from napari_harpy.core.spatial_query.canonical_models import (
    CanonicalCacheMismatch,
    CanonicalCacheReport,
    CanonicalCacheState,
    CanonicalCacheUpdateAction,
    CanonicalCacheUpdatePayload,
    CanonicalCacheUpdateResult,
    CanonicalCentersResult,
    CanonicalMetadata,
    CanonicalMismatchCode,
    CanonicalRegionBinding,
    CanonicalRegionMetadata,
    CanonicalSourceSignature,
    SpatialDimension,
    build_instance_set_digest,
)
from napari_harpy.core.spatial_query.centroids import (
    calculate_canonical_centers,
    ensure_canonical_centers,
)
from napari_harpy.core.spatial_query.query import (
    build_canonical_center_query_request,
    evaluate_canonical_center_query,
)
from napari_harpy.core.spatial_query.query_models import (
    CanonicalCenterQueryRequest,
    CanonicalCenterQueryResult,
)

__all__ = [
    "CANONICAL_ALGORITHM_VERSION",
    "CANONICAL_AXES",
    "CANONICAL_CACHE_PATHS",
    "CANONICAL_OBSM_KEY",
    "CANONICAL_SCHEMA_VERSION",
    "SPATIAL_COORDINATES_KEY",
    "CanonicalCenterQueryRequest",
    "CanonicalCenterQueryResult",
    "CanonicalCacheMismatch",
    "CanonicalCacheReport",
    "CanonicalCacheState",
    "CanonicalCacheUpdateAction",
    "CanonicalCacheUpdatePayload",
    "CanonicalCacheUpdateResult",
    "CanonicalCentersResult",
    "CanonicalMetadata",
    "CanonicalMismatchCode",
    "CanonicalRegionBinding",
    "CanonicalRegionMetadata",
    "CanonicalSourceSignature",
    "SpatialDimension",
    "apply_canonical_cache_update",
    "build_canonical_cache_update_payload",
    "build_canonical_center_query_request",
    "build_canonical_metadata",
    "build_canonical_region_binding",
    "build_canonical_source_signature",
    "build_instance_set_digest",
    "calculate_canonical_centers",
    "canonical_metadata_to_storage",
    "inspect_canonical_cache",
    "ensure_canonical_centers",
    "evaluate_canonical_center_query",
    "parse_canonical_metadata",
]
